spring.application.name=StaffManagementSystem

# Microsoft SQL Server (Direct Port 1433) Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=StaffManagementDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=StrongPassword123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate / JPA configuration
# Using 'none' because all tables, constraints, and keys are already managed via SQL script in SSMS
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

server.port=8080
spring.thymeleaf.cache=false
